alias: Telefon Anrufliste
description: Anleitung unter https://github.com/der8en/Fritz-Call-Monitor-Feed
trigger:
  - platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    id: "1"
    from: dialing
    to: talking
    alias: ausgehend
  - alias: klingelt
    platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    id: "2"
    to: ringing
    for:
      hours: 0
      minutes: 0
      seconds: 2
  - platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    id: "3"
    from: ringing
    to: talking
    alias: ankommend
  - platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    id: "4"
    from: ringing
    to: idle
    alias: verpasst
  - platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    to: ringing
    for:
      hours: 0
      minutes: 0
      seconds: 30
    enabled: false
    alias: Zeit für AB nach X Sekunden (abzgl. 1 Sekunde)
    id: "5"
  - alias: Feed bereinigen
    platform: state
    entity_id:
      - sensor.fritz_box_7490_anrufmonitor_telefonbuch
    for:
      hours: 0
      minutes: 0
      seconds: 2
    to: idle
    id: "6"
    enabled: true
condition:
  - condition: or
    conditions:
      - condition: trigger
        id:
          - "1"
          - "2"
          - "5"
          - "6"
      - condition: and
        conditions:
          - condition: trigger
            id:
              - "3"
              - "4"
          - condition: state
            entity_id: input_boolean.telefon_klingelt
            state: "on"
action:
  - alias: Ausgehend
    if:
      - condition: trigger
        id: "1"
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#8BBF68"><ha-icon icon="mdi:phone-outgoing">
            </ha-icon></font> Gespräch mit
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","with")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_feed
  - alias: Klingelt
    if:
      - condition: trigger
        id:
          - "2"
    then:
      - service: input_boolean.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
      - service: input_text.set_value
        data:
          value: >-
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","from")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "from_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "from_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_anrufer
  - alias: "V1: Ankommend (ohne Geschäftszeiten)"
    if:
      - condition: trigger
        id:
          - "3"
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#268DDA"><ha-icon icon="mdi:phone-incoming">
            </ha-icon></font> Anruf von
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","with")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_feed
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
    enabled: true
  - alias: "V2: Ankommend (innerhalb Geschäftszeiten)"
    if:
      - condition: trigger
        id:
          - "3"
      - condition: or
        conditions:
          - condition: time
            after: "08:00:00"
            before: "18:30:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: "08:00:00"
            before: "13:30:00"
            weekday:
              - sat
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#268DDA"><ha-icon icon="mdi:phone-incoming">
            </ha-icon></font> Anruf von
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","with")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_feed
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
    enabled: false
  - alias: "V2: AB (außerhalb Geschäftszeiten)"
    if:
      - condition: trigger
        id:
          - "3"
      - condition: or
        conditions:
          - condition: time
            after: "18:30:00"
            before: "08:00:00"
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
          - condition: time
            after: "13:30:00"
            before: "08:00:00"
            weekday:
              - sat
          - condition: time
            weekday:
              - sun
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#E3603B"><ha-icon icon="mdi:phone-lock">
            </ha-icon></font> Anruf auf AB von
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","with")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "with_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_feed
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
    enabled: false
  - alias: AB nach X Sekunden
    if:
      - condition: trigger
        id:
          - "5"
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#268DDA"><ha-icon icon="mdi:phone-message">
            </ha-icon></font> Anruf auf AB von
            {{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch","from")}}
            {% if (state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "from_name") == "unknown") %}(Unbekannt{% else
            %}({{state_attr("sensor.fritz_box_7490_anrufmonitor_telefonbuch",
            "from_name")}}{% endif %})
        target:
          entity_id: input_text.telefon_feed
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
  - alias: Verpasst
    if:
      - condition: trigger
        id:
          - "4"
    then:
      - service: input_text.set_value
        data:
          value: >-
            <font color="#E3603B"><ha-icon icon="mdi:phone-missed">
            </ha-icon></font> Verpasster Anruf von
            {{states("input_text.telefon_anrufer")}}
        target:
          entity_id: input_text.telefon_feed
      - service: input_boolean.turn_off
        metadata: {}
        data: {}
        target:
          entity_id: input_boolean.telefon_klingelt
  - if:
      - condition: trigger
        id:
          - "6"
    then:
      - service: input_text.set_value
        data:
          value: unknown
        target:
          entity_id: input_text.telefon_feed
    alias: Feed bereinigen
mode: single
